import type { Property, Agent } from "./types"

export const mockProperties: Property[] = [
  {
    id: "1",
    slug: "luxury-villa-ocean-view-punta-cana",
    title: "Villa de Lujo con Vista al Océano",
    operation: "venta",
    propertyType: "villa",
    status: "activa",
    price: 850000,
    currency: "USD",
    bedrooms: 4,
    bathrooms: 3,
    parking: 2,
    areaBuilt: 350,
    areaLot: 500,
    furnished: true,
    amenities: ["Piscina", "Vista al Mar", "Jardín", "Seguridad 24/7"],
    city: "Punta Cana",
    zone: "Cap Cana",
    address: "Cap Cana Marina",
    lat: 18.5601,
    lng: -68.3725,
    agentId: "agent1",
    featured: true,
    description:
      "Espectacular villa de 4 habitaciones con vistas panorámicas al océano, piscina privada y amenidades modernas en exclusiva comunidad de Punta Cana.",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "2",
    slug: "modern-apartment-santo-domingo",
    title: "Apartamento Moderno en el Centro",
    operation: "alquiler",
    propertyType: "apartamento",
    status: "activa",
    price: 2500,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2,
    parking: 1,
    areaBuilt: 120,
    furnished: false,
    amenities: ["Vista a la Ciudad", "Balcón", "Ascensor", "Seguridad"],
    city: "Santo Domingo",
    zone: "Zona Colonial",
    address: "Zona Colonial",
    lat: 18.4861,
    lng: -69.9312,
    agentId: "agent2",
    featured: false,
    description:
      "Contemporáneo apartamento de 2 habitaciones en el corazón de Santo Domingo con vistas a la ciudad y acabados premium.",
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-01-20T00:00:00Z",
  },
  {
    id: "3",
    slug: "beachfront-condo-bavaro",
    title: "Condominio Frente al Mar",
    operation: "venta",
    propertyType: "apartamento",
    status: "activa",
    price: 450000,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2,
    parking: 1,
    areaBuilt: 180,
    furnished: true,
    amenities: ["Acceso a Playa", "Piscina", "Gimnasio", "Concierge"],
    city: "Bávaro",
    zone: "Playa Bávaro",
    address: "Playa Bávaro",
    lat: 18.6813,
    lng: -68.409,
    agentId: "agent1",
    featured: true,
    description:
      "Espectacular condominio de 3 habitaciones frente al mar con acceso directo a la playa y amenidades tipo resort.",
    createdAt: "2024-01-25T00:00:00Z",
    updatedAt: "2024-01-25T00:00:00Z",
  },
]

export const mockAgents: Agent[] = [
  {
    id: "agent1",
    slug: "maria-rodriguez",
    name: "María Rodríguez",
    email: "maria@valiahome.com",
    phone: "+1-809-816-6766",
    whatsapp: "+18098166766",
    photoUrl: "/professional-woman-realtor.png",
    bio: "Especialista en propiedades de lujo con más de 8 años en el mercado dominicano. Fluente en español, inglés y francés.",
    specialties: ["Propiedades de Lujo", "Casas Frente al Mar", "Propiedades de Inversión"],
    experience: 8,
    languages: ["Español", "Inglés", "Francés"],
    properties: ["1", "3"],
    rating: 4.9,
    reviews: 47,
    createdAt: "2020-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "agent2",
    slug: "carlos-mendez",
    name: "Carlos Méndez",
    email: "carlos@valiahome.com",
    phone: "+1-809-816-6766",
    whatsapp: "+18098166766",
    photoUrl: "/professional-realtor.png",
    bio: "Experto en bienes raíces comerciales y residenciales especializado en propiedades de Santo Domingo. Conocido por su servicio excepcional al cliente.",
    specialties: ["Propiedades Comerciales", "Apartamentos Urbanos", "Compradores Primerizos"],
    experience: 6,
    languages: ["Español", "Inglés"],
    properties: ["2"],
    rating: 4.8,
    reviews: 32,
    createdAt: "2021-03-15T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "agent3",
    slug: "ana-garcia",
    name: "Ana García",
    email: "ana@valiahome.com",
    phone: "+1-809-816-6766",
    whatsapp: "+18098166766",
    photoUrl: "/professional-woman-realtor.png",
    bio: "Agente especializada en propiedades vacacionales y de inversión en la costa este. Más de 5 años ayudando a clientes internacionales.",
    specialties: ["Propiedades Vacacionales", "Inversión Extranjera", "Condominios"],
    experience: 5,
    languages: ["Español", "Inglés", "Italiano"],
    properties: [],
    rating: 4.7,
    reviews: 28,
    createdAt: "2022-06-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
]
